export const GET_EVENTS_SUCCESS = 'GET_EVENTS_SUCCESS'
export const GET_EVENTS_FAILURE = 'GET_EVENTS_FAILURE'
export const FILTER_BY_ZIPCODE = 'FILTER_BY_ZIPCODE'
export const CLEAR_ZIPCODE = 'CLEAR_ZIPCODE'
